Repository SOEN-343-Org/Smart-Home-Simulator, pull requests merged in 2020-10, with the labels that each got.

#14 Update README.md
  README.md
Labels: documentation

#18 Read draw house layout (2) modified
  src/main/java/org/soen343/controller/HouseLayoutController.java
  src/main/java/org/soen343/util/HouseLayoutUtil.java
Labels: CODE REVIEW

#23 Profile selection and observer pattern between Individual and Room
  pom.xml
  src/main/Home simulator db.sql
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/module-info.java
  src/main/java/org/soen343/connection/DBConnection.java
  src/main/java/org/soen343/controller/IndividualController.java
  src/main/java/org/soen343/models/Individual.java
  src/main/java/org/soen343/models/Observer.java
  src/main/java/org/soen343/models/Reporter.java
  src/main/java/org/soen343/models/Room.java
  src/main/java/org/soen343/util/HouseLayoutUtil.java
  src/main/resources/org/soen343/individual.fxml
Labels: CODE REVIEW

#17 Login/signup view
  src/main/resources/org/soen343/login.fxml
Labels: CODE REVIEW, frontend

#27 Shs module
  src/main/java/org/soen343/controllers/Controller.java
  src/main/java/org/soen343/controllers/DashboardController.java
  src/main/java/org/soen343/controllers/IndividualController.java
  src/main/java/org/soen343/controllers/SimulationContextController.java
  src/main/java/org/soen343/controllers/SimulationInfoController.java
  src/main/java/org/soen343/controllers/SmartHomeContextController.java
  src/main/java/org/soen343/controllers/SmartHomeCoreController.java
  src/main/java/org/soen343/models/House.java
  src/main/java/org/soen343/models/Individual.java
  src/main/java/org/soen343/models/Model.java
  src/main/java/org/soen343/models/Time.java
  src/main/java/org/soen343/models/User.java
  src/main/resources/org/soen343/DashboardView.fxml
  src/main/resources/org/soen343/IndividualView.fxml
  src/main/resources/org/soen343/SimulationContextView.fxml
  src/main/resources/org/soen343/SimulationInfoView.fxml
  src/main/resources/org/soen343/SmartHomeContextView.fxml
  src/main/resources/org/soen343/SmartHomeCoreView.fxml
Labels: CODE REVIEW

#32 Context temp
  src/main/java/org/soen343/controllers/DashboardController.java
  src/main/java/org/soen343/controllers/SimulationInfoController.java
  src/main/java/org/soen343/controllers/SmartHomeSimulatorModuleController.java
  src/main/java/org/soen343/models/DateTime.java
  src/main/java/org/soen343/models/Model.java
  src/main/java/org/soen343/models/OutsideTemperature.java
  src/main/java/org/soen343/services/SimulationInfoService.java
  src/main/java/org/soen343/services/SmartHomeSimulatorModuleService.java
  src/main/resources/org/soen343/SimulationInfoView.fxml
  src/main/resources/org/soen343/SmartHomeSimulatorModuleView.fxml
  src/main/resources/org/soen343/img/home.jpg
  src/main/resources/org/soen343/img/profile-placeholder.jpg
Labels: CODE REVIEW
